# Generated by Django 3.0.14 on 2024-10-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Valid_to',
            new_name='valid_to',
        ),
    ]
